# Use a base image of Python
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the requirements.txt for tests into the image
COPY tests/requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code into the image
COPY . .

# Run the tests
CMD ["pytest", "--maxfail=1", "--disable-warnings", "-q"]