export const SURPRISE_INTERESTS = [
    "art galleries, street art, murals",
    "craft beer, brewery tours, pubs",
    "street food, local markets, food halls",
    "history, castles, ancient ruins",
    "nature, parks, gardens, scenic viewpoints",
    "live music, jazz bars, concert venues",
    "coffee shops, bakeries, brunch spots",
    "museums, cultural centres, exhibitions",
    "nightlife, bars, clubs",
    "architecture, historic buildings, monuments",
    "theatre, opera, performing arts",
    "wine bars, vineyards, tapas",
    "hiking, waterfalls, nature reserves",
    "vintage shops, bookstores, antiques",
    "sports, stadiums, outdoor activities",
    "temples, mosques, churches, spiritual sites",
    "aquarium, zoo, botanical garden",
    "rooftop bars, panoramic viewpoints",
    "street markets, bazaars, flea markets",
    "film locations, cinemas, pop culture",
];
